spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: yzh
    password: ww284TSKD7iHJfhn
    url: jdbc:mysql://124.222.1.13:3319/homework?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5       # 初始线程数
      max-active: 20        # 最大线程数
      max-wait: 60000       # 最大等待时间
      time-between-eviction-runs-millis: 60000      # 最大空闲实践
      min-idle: 5
mybatis-plus:
  type-aliases-package: org.jirafa.homework.entity
  mapper-locations: classpath:org/jirafa/homework/Mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8099